import './globals.scss';
import { CartProvider } from "@/app/context/CartContext";

export const metadata = {
  title: "Quote Reference Library",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartProvider>
      <html lang="en">
      <body>{children}</body>
      </html>
    </CartProvider>
  );
}
