import './globals.scss';
import { CartProvider } from "@/app/context/CartContext";
import { HeartsProvider } from "@/app/context/HeartContext";

export const metadata = {
  title: "Quote Reference Library",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartProvider>
      <HeartsProvider>
        <html lang="en">
        <body>{children}</body>
        </html>
      </HeartsProvider>
    </CartProvider>
  );
}
